/**
 * Resolves an artifact argument to its base64url hash.
 * Accepts: an .altweb.html file (altweb-hash meta), an .altweb file (raw hash),
 * a URL with a #hash, or the hash itself.
 */
import { existsSync, readFileSync } from 'node:fs';

const HASH_META_RE = /<meta name="altweb-hash" content="([A-Za-z0-9_-]+)">/;

export function resolveHash(arg: string): string {
  if (existsSync(arg)) {
    const content = readFileSync(arg, 'utf8');
    const trimmed = content.trim();

    if (trimmed.startsWith('<')) {
      const match = trimmed.match(HASH_META_RE);
      if (!match) {
        throw new Error(
          `${arg}: missing the altweb-hash meta tag — not a standalone ALTWEB artifact (or generated by an old version; regenerate it)`
        );
      }
      return match[1];
    }
    // .altweb or a text file with a raw hash (tolerates the "alt " prefix)
    return trimmed.replace(/^alt\s+/, '');
  }

  if (arg.startsWith('http://') || arg.startsWith('https://')) {
    const fragment = arg.split('#')[1];
    if (!fragment) {
      throw new Error(`${arg}: URL missing the #hash fragment`);
    }
    return fragment;
  }

  return arg.replace(/^alt\s+/, '').replace(/^#/, '');
}
